# -*- coding: utf-8 -*-
"""question_1e.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BZ9Oxb7V5Wt01S267xkC86LagYD-sPVI
"""

#importing libraries
import numpy as np
from scipy import linalg

M = np.array([[1,2], [2,1], [3,4], [4,3]])
print(M)

"""(a) Compute the SVD of M (Use scipy.linalg.svd function in Python and set the
argument full matrices to False). The function returns values corresponding to U, Σ and $V^{T}$. What are the values returned for U, Σ and $V^{T}$? Note: Make sure that the first element of the returned array Σ has a greater value than the second element.
"""

U, S, V_T = linalg.svd(M, full_matrices = False)
print("U = ", U)
print("Sigma=", S)
print("V_transpose= ", V_T)

"""(b) Compute the eigenvalue decomposition of $M^{T}M$ (Use scipy.linalg.eigh function in Python). The function returns two parameters: a list of eigenvalues (let us call this list Evals) and a matrix whose columns correspond to the eigenvectors of the respective eigenvalues (let us call this matrix Evecs). Sort the list Evals in descending order such that the largest eigenvalue appears first in the list. Also, re-arrange the columns in
Evecs such that the eigenvector corresponding to the largest eigenvalue appears in the first column of Evecs. What are the values of Evals and Evecs (after the sorting and re-arranging process)?
"""

M_TM = np.matmul(np.transpose(M),M)
Evals, Evecs = linalg.eigh(M_TM)

a = Evals.argsort()[::-1]   
Evals = Evals[a]
Evecs = Evecs[:,a]
print("Evals =\n", Evals)
print("Evecs =\n", Evecs)

"""(d) Based on the experiment and the expressions obtained in part (c) and part
(d) for $M^{T}M$, what is the relationship (if any) between the eigenvalues of $M^{T}M$ and the singular values of M? Explain.
"""

print("Eigen values of M_Transpose_M = ", Evals)
print("Singular values of M = ", S)
print("sqrt MtM =", np.sqrt(Evals))